Dev
liliamyhaliuk/think-python pull request #1
Opened 2022-05-11 21:10 UTC by liliamyhaliuk

Adding exercises: 1.8 (Exercise 4), 2.12 (Exercise 2).

2022-05-13 19:27 UTC, auraz requested changes
Looking very good, but require some improvements.

2022-05-13 19:27 UTC, auraz commented on chapter1/1.9_exercise_2.py
> +avg_pace_sec = total_seconds / full_distance
this should be printed too

2022-05-13 19:27 UTC, auraz commented on chapter2/2.10_exercise_2.py
> +print('The volume of a sphere: ', (4 / 3 * math.pi * radius**3))
JFYI that in python2, it will be the wrong answer.

2022-05-13 19:27 UTC, auraz commented on chapter1/1.9_exercise_2.py
> +#Exercises of the book "Think python"
The file should be named 1.9.2.py

2022-05-13 19:27 UTC, auraz commented on chapter1/1.9_exercise_2.py
> +# 1. How many seconds are there in 42 minutes 42 seconds?
Very good, that you've included tasks! 👍🏻

2022-05-13 19:27 UTC, auraz commented on chapter2/2.10_exercise_2.py
> +s_cost_first = 3 #shipping_cost for the first copy
JDYI PEP8 requires 2 spaces before comment and 1 space after #.

2022-05-13 19:27 UTC, auraz commented on chapter2/2.10_exercise_2.py
> +print('Total wholesale cost for 60 copies: ', sum)
Answer is different, need to investigate

2022-05-13 19:27 UTC, auraz commented on chapter2/2.10_exercise_2.py
> +print('Total wholesale cost for 60 copies: ', sum)
Should be (1-discount).

2022-05-13 19:27 UTC, auraz commented on chapter2/2.10_exercise_2.py
> +print('Total wholesale cost for 60 copies: ', sum)
Also ensure precision is correct.

2022-05-13 19:27 UTC, auraz commented on chapter2/2.10_exercise_2.py
> +#function convert time from str format('07:12', MM:SS) to amount of seconds
Very good that you're wring docstring!
According to PEP8, they should be written as:
```
def time_to_seconds(time: str):
     """Function convert time from str format('07:12', MM:SS) to amount of seconds."""
      return (int(time[ : time.find(':')]) * 60) + (int(time[time.find(':') + 1 : ]))
```

2022-05-13 19:27 UTC, auraz commented on chapter2/2.10_exercise_2.py
> +print("You will get home at: ", home_time)
This is correct!

2022-05-14 09:06 UTC, auraz commented on chapter2/2.10_exercise_2.py
> +s_cost_first = 3 #shipping_cost for the first copy
`s_cost_first = 3  # Shipping_cost for the first copy.

2022-05-14 09:06 UTC, auraz commented on chapter2/2.10_exercise_2.py
> +s_cost_first = 3 #shipping_cost for the first copy
`s_cost_first = 3  # Shipping_cost for the first copy.

2022-05-14 09:10 UTC, auraz requested changes

2022-05-14 09:10 UTC, auraz commented on chapter2/2.10_exercise_2.py
> +#Exercises of the book "Think python"
```
"""
Exercises of the book "Think python"
2.10 Exercises
"""
```

2022-05-16 20:29 UTC, liliamyhaliuk commented on chapter1/1.9_exercise_2.py
> +print(avg_speed)
Done.

2022-05-16 20:31 UTC, liliamyhaliuk commented on chapter1/1.9_exercise_2.py
> +avg_pace_min = avg_pace_sec // 60 + (int(avg_pace_sec % 60) / 100)
It's a mistake. We don't need to do this operation here. I deleted it.

2022-05-16 20:31 UTC, liliamyhaliuk commented on chapter1/1.9_exercise_2.py
> +avg_pace_sec = total_seconds / full_distance
Done.

2022-05-16 20:34 UTC, liliamyhaliuk commented on chapter2/2.10_exercise_2.py
> +s_cost_first = 3 #shipping_cost for the first copy
I installed the plugin "black" as needed so it fixed these mistakes. Thank you!

2022-05-16 20:37 UTC, liliamyhaliuk commented on chapter2/2.10_exercise_2.py
> +print('Total wholesale cost for 60 copies: ', sum)
Found this mistake. The answer should be correct now.
Also, I took care of precision, thank you.

2022-05-16 20:38 UTC, liliamyhaliuk commented on chapter2/2.10_exercise_2.py
> +#function convert time from str format('07:12', MM:SS) to amount of seconds
I added docstring to the right place in this function. Thank you!

2022-05-16 20:42 UTC, merged

2022-05-17 06:43 UTC, auraz commented on chapter1/1.9_exercise_2.py
> +avg_pace_min = avg_pace_sec // 60 + (int(avg_pace_sec % 60) / 100)
Thank you

2022-05-17 06:43 UTC, auraz commented on chapter1/1.9_exercise_2.py
> +#Exercises of the book "Think python"
Thank you

2022-05-17 06:44 UTC, auraz commented on chapter2/2.10_exercise_2.py
> +s_cost_first = 3 #shipping_cost for the first copy
Thank you

2022-05-17 06:44 UTC, auraz commented on chapter2/2.10_exercise_2.py
> +print('Total wholesale cost for 60 copies: ', sum)
Thank you

2022-05-17 06:44 UTC, auraz commented on chapter2/2.10_exercise_2.py
> +#function convert time from str format('07:12', MM:SS) to amount of seconds
Thank you