Exercises 13.1.7, 13.1.8 from think python
liliamyhaliuk/think-python pull request #11
Opened 2022-07-29 20:56 UTC by liliamyhaliuk

Hi! 
I've done new exercises from the book think python. 
Please check when you have time. Thank you!

(13.1.8 - there are not all tasks but the main point is done. )

2022-08-03 08:31 UTC, auraz requested changes
Started initial review (partial)?

2022-08-03 08:31 UTC, auraz commented on chapter13/13.1.7.py
> +                    all_words[word] = all_words[word] + 1
Maybe `all_words[word] = all_words.get(word, 0) + 1` will work instead lines 54-56?

2022-08-03 08:31 UTC, auraz commented on chapter13/13.1.7.py
> +            current_sum = freq_dict[i] + last_sum
Can we move last_sum with initial value outside of the loop and get rid of `if not result`?

2022-08-03 08:31 UTC, auraz commented on chapter13/13.1.8.py
> +        replace_dict.setdefault(ord(c), "")
why not `replace_dict[ord(c)]` = "" if it is faster?

2022-08-03 08:31 UTC, auraz commented on chapter13/13.1.8.py
> +def get_all_words_in_book(PATH):
Good!

2022-08-06 14:29 UTC, auraz requested changes
Looks good, please address comments and do not forget the punctuation in the Markov exercise (you can use approach from the task: do not cut . from the words initially). Please generate ~50 words.

2022-08-06 14:29 UTC, auraz commented on chapter13/13.1.8.py
> +        if markov_dict.get(prefix) is not None:
`is not None` not needed, unless prefix is empty string.

2022-08-06 14:29 UTC, auraz commented on chapter13/13.1.8.py
> +        # Add prefix and suffix to the list
To the dict

2022-08-06 14:29 UTC, auraz commented on chapter13/13.1.8.py
> +            markov_dict[prefix] = [suffix]
good example for setdefault?

2022-08-07 20:05 UTC, liliamyhaliuk commented on chapter13/13.1.7.py
> +                    all_words[word] = all_words[word] + 1
This is really much better. I have a lot to learn))
Thank you!

2022-08-07 20:11 UTC, liliamyhaliuk commented on chapter13/13.1.7.py
> +            current_sum = freq_dict[i] + last_sum
I've moved the initial value out of the loop and made the loop go through an already created and sorted list of unique words instead of sorting the dictionary again
Thank you for making me think about this!

2022-08-07 20:13 UTC, liliamyhaliuk commented on chapter13/13.1.8.py
> +        replace_dict.setdefault(ord(c), "")
I guess that I get used to "setdefault"... Your suggestion would be much better. You are right
But I deleted this code since we have to keep punctuation

2022-08-07 20:14 UTC, liliamyhaliuk commented on chapter13/13.1.8.py
> +def get_all_words_in_book(PATH):
Thank you!)

2022-08-07 20:14 UTC, liliamyhaliuk commented on chapter13/13.1.8.py
> +        # Add prefix and suffix to the list
Thank you!)

2022-08-07 20:16 UTC, liliamyhaliuk commented on chapter13/13.1.8.py
> +            markov_dict[prefix] = [suffix]
Yeah, totally. I even checked if it affects the time and it doesn't, so I've changed these lines to setdefault. Thank you so much!)

2022-08-07 20:18 UTC, liliamyhaliuk commented
Hi!
I've addressed the comments and changed the code a little bit as you suggested. 
Please, check when you have time. Thank you!

2022-08-10 07:42 UTC, auraz approved these changes

2022-08-10 07:58 UTC, merged