Dev think python4
liliamyhaliuk/think-python pull request #12
Opened 2022-08-16 08:51 UTC by liliamyhaliuk

Hello!
I've done new exercises from the book Think Python (chapter 14 and chapter 15( not done yet))
Please, check when you have time.
Thank you!

2022-08-16 09:25 UTC, auraz requested changes

2022-08-16 09:25 UTC, auraz commented on chapter15/15.9.2.py
> +    def __init__(self, cornerA, cornerB, cornerC, cornerD):
change to one point, width, height.

2022-08-16 09:25 UTC, auraz commented on chapter15/15.9.2.py
> +    def get_distance_between_points(self, pointA, pointB):
def distance_from_the_point(self, pointB)

2022-08-18 08:57 UTC, auraz requested changes

2022-08-18 08:57 UTC, auraz commented on chapter15/15.9.2.py
> +    def get_distance_between_points(self, pointA, pointB):
point A is not needed here, why?

2022-08-21 20:00 UTC, liliamyhaliuk commented on chapter15/15.9.2.py
> +
I deleted the method get distance from the pointA to pointB since it's not necessary anymore.

2022-08-21 20:00 UTC, liliamyhaliuk commented on chapter15/15.9.2.py
> +    def get_distance_between_points(self, pointA, pointB):
I deleted the method get distance from the pointA to pointB since it's not necessary anymore.

2022-08-21 20:05 UTC, liliamyhaliuk commented on chapter15/15.9.2.py
> +
I've changed the constructor of the rectangle class as you suggested. From 4 points as arguments to the start point, height, and width

2022-08-21 20:05 UTC, liliamyhaliuk commented on chapter15/15.9.2.py
> +    def __init__(self, cornerA, cornerB, cornerC, cornerD):
I've changed the constructor of the rectangle class as you suggested. From 4 points as arguments to the start point, height, and width
Thank you!

2022-08-23 15:48 UTC, auraz approved these changes
Looks good!

2022-08-25 19:07 UTC, merged