Exercises from chapter3
liliamyhaliuk/think-python pull request #4
Opened 2022-05-19 19:33 UTC by liliamyhaliuk

I did all exercises from chapter 3 of the book "Think Python". Please, check when you have time.
I'm not sure about the 3 exercise. It looks like my decision is too big but using concatenation is forbidden by the definition of this exercise...

2022-05-20 06:04 UTC, auraz requested changes
Good! Please address comments.

2022-05-20 06:04 UTC, auraz commented on chapter3/3.14.2.py
> +do_four(print_spam, 'spam')
Correct

2022-05-20 06:04 UTC, auraz commented on chapter3/3.14.3.py
> +# 2. Write a function that draws a similar grid with four rows and four columns.
only 2 rows for me.

2022-05-23 17:38 UTC, liliamyhaliuk commented on chapter3/3.14.1.py
> +    '''Move argument to the left so the last letter of the argument is in column 70 of display'''
Hi!
I updated the docstring in all functions with the right quotation mark.

2022-05-23 17:38 UTC, liliamyhaliuk commented on chapter3/3.14.1.py
> +right_justify('s')
Thank you for checking!

2022-05-23 17:38 UTC, liliamyhaliuk commented on chapter3/3.14.2.py
> +do_four(print_spam, 'spam')
Thank you!

2022-05-23 17:56 UTC, auraz approved these changes
Much better!

2022-05-24 17:26 UTC, merged