Chapter 10, 11 from Think Python
liliamyhaliuk/think-python pull request #9
Opened 2022-06-28 21:37 UTC by liliamyhaliuk

Hello!
I did all exercises from chapter 10 and 1 from chapter 11. 
Please check when you have time. Thank you!

2022-06-29 06:51 UTC, auraz requested changes

2022-06-29 06:51 UTC, auraz commented on chapter10/10.15.6.py
> +    for letter in word1:
good, what you think about another solution, when you sort two lists and compare them?

2022-06-29 06:51 UTC, auraz commented on chapter10/10.15.8.py
> +# function in the random module.
Where is the code?

2022-06-29 06:51 UTC, auraz commented on chapter10/10.15.9.py
> +print("Idiom: --- %s seconds ---" % (time.time() - start_time))
Why one solution is longer?

2022-06-29 06:51 UTC, auraz commented on chapter10/10.15.10.py
> +    """Function search for the target in the list of words by using bisecting search"""
Is this your solution or have you copied his?

2022-06-29 06:51 UTC, auraz commented on chapter10/10.15.12.py
> +    for word1 in words:
Please make sure that both words should be of the same length.

2022-06-29 11:31 UTC, liliamyhaliuk commented on chapter10/10.15.10.py
> +    """Function search for the target in the list of words by using bisecting search"""
Hi. 
No, it's not all my idea. 
I added my idea in file 10.15.10_test.py but my algorithm didn't work with words from the file words.txt.
I have no clue why since it's working fine with my test cases.
I couldn't find a mistake so I checked the solution and took the idea by passing the cut list to the function.

2022-06-29 16:38 UTC, auraz requested changes

2022-07-05 22:04 UTC, liliamyhaliuk commented on chapter10/10.15.6.py
> +    for letter in word1:
That's a great idea. 
I did this in my program and got rid of the loop))
Please check if I got this right.
Thank you!

2022-07-05 22:05 UTC, liliamyhaliuk commented on chapter10/10.15.8.py
> +# function in the random module.
I guess that I missed this file by mistake.
I did this exercise in my last commit. Please check when you have time. Thank you!

2022-07-05 22:06 UTC, liliamyhaliuk commented on chapter10/10.15.9.py
> +print("Idiom: --- %s seconds ---" % (time.time() - start_time))
Because when we are using the solution with "idiom" the program is creating an entirely new list whenever we want to add a new word instead of extending an already existing list - that's my guess. 
Is it correct?

2022-07-05 22:10 UTC, liliamyhaliuk commented
I added fixes for chapter 10, exercises from chapter 11 (without exercise 6 - I'll do it for next time), and chapter 12. Please, check when you have time. Thank you!

2022-07-06 07:14 UTC, auraz requested changes

2022-07-12 15:53 UTC, liliamyhaliuk commented
Hi! I've fixed exercises 10.15.10_test and 10.15.12. They both work but 10.15.12 is really slow tho...

2022-07-15 10:06 UTC, auraz requested changes
You did a lot of good work!

2022-07-15 10:06 UTC, auraz commented on chapter12/12.10.3.py
> +                    if val not in anagrams.get(key):
Could be usecase for setdefault.

2022-07-15 10:06 UTC, auraz commented on chapter12/12.10.3.py
> +    """The function checks how many letters are different in two words"""
This type of function are called "distance function", you calculate how far two words from each other using some metric. Good idea!

2022-07-15 10:06 UTC, auraz commented on chapter12/12.10.3.py
> +            index2 = words.index(word) + 1
if you know that it is second, why not use [ ] operation, like words[1]?

2022-07-15 10:06 UTC, auraz commented on chapter12/12.10.4.py
> +                reduced_words.setdefault(word, [])
why not use a[b] = c idiom?

2022-07-15 10:06 UTC, auraz commented on chapter12/12.10.4.py
> +    if len(word) == 1:
that is not correct, "k" is not a word.

2022-07-15 10:06 UTC, auraz commented on chapter12/12.10.4.py
> +            return check_if_reducable(n_word)
good way of using recursion, well done.

2022-07-15 19:57 UTC, liliamyhaliuk commented on chapter10/10.15.12.py
> +        for word2 in words:
I've fixed my solution, but I wanted to let you know that I remembered the right way to get it done because I already checked the solution from the book when my idea was working really slow.

2022-07-15 19:58 UTC, liliamyhaliuk commented on chapter10/10.15.6.py
> +    letters_word1 = sorted(list(word1))
Right, I forgot that strings work almost like lists. I've fixed it, thank you!

2022-07-15 19:59 UTC, liliamyhaliuk commented on chapter10/10.15.8.py
> +Exercises of the book "Think python"
Done. Please check when you have time. Thank you!

2022-07-15 20:00 UTC, liliamyhaliuk commented on chapter12/12.10.3.py
> +    """The function checks how many letters are different in two words"""
Thank you!))

2022-07-15 20:09 UTC, liliamyhaliuk commented on chapter12/12.10.4.py
> +                reduced_words.setdefault(word, [])
We have to create a new key with an empty list only if it doesn't already exist.
We this idiom we have to add another line of code for checking if the key already exists.
Method setdefault is doing it already. 
Is it better to use this idiom?

2022-07-15 20:11 UTC, liliamyhaliuk commented on chapter12/12.10.4.py
> +    if len(word) == 1:
You are right. We have to specify that one - letter word is only "I". Thank you. I've fixed my solution. Please check when you have time.

2022-07-15 20:16 UTC, liliamyhaliuk commented on chapter12/12.10.4.py
> +            return check_if_reducable(n_word)
Thank you so much))
This book is really teaching me thinking in a different way. Before reading it I would done this exercise it with loop - 100%. 
So thank you)

2022-07-16 11:24 UTC, auraz requested changes

2022-07-16 11:24 UTC, auraz commented on chapter12/12.10.4.py
> +    if len(word) == 1:
a too

2022-07-16 11:24 UTC, auraz commented on chapter10/10.15.8.py
> +    return count_probability
Fix birthday dates and count probability correctly.

2022-07-16 11:24 UTC, auraz commented on chapter11/11.10.6.py
> +                new_word1 = i[1:]
was wrong, in condition, we need to remove 1st or 2nd letter.

2022-07-29 15:55 UTC, liliamyhaliuk commented on chapter10/10.15.8.py
> +    return count_probability
Hi!
I've fixed the algorithm for probability and dates for birthdays. 
It works correctly now and the percent of the same birthdays in 1000 simulations is more than 50 for real!))

2022-07-29 16:09 UTC, liliamyhaliuk commented on chapter11/11.10.5.py
> +        # Create rotate word
Hi, I moved the algorithm for rotating word into another function.

2022-07-29 16:18 UTC, liliamyhaliuk commented on chapter11/11.10.4.py
> +    return False
I don't know why your comment disappeared.... but you suggested using list_dict[i] = 1 instead of list_dict.setdefault(i, ""). I've done that
And I wanted to share with you that it's improved the speed of the function quite a lot! Thank you!)

2022-07-30 10:46 UTC, auraz approved these changes

2022-08-03 06:44 UTC, merged